let opt1=document.getElementById("opt1");
let opt2=document.getElementById("opt2");
let opt3=document.getElementById("opt3");
let opt4=document.getElementById("opt4");
let start_all=document.getElementById("start_all");
let status=document.getElementById("status");
let donat=document.getElementById("donat");
let residence=document.getElementById("residence");
let residence_status=document.getElementById("residence-status");
opt1.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:opt_1,})});
opt2.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:opt_2,})});
opt3.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:opt_3,})});
opt4.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:opt_4,})});
start_all.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:start_all_opt,})});
status.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:status_opt,})});
donat.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:donata_usdt(),})});
residence.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:residence_ru(),})});
residence_status.addEventListener("click",async()=>{let[tab]=await chrome.tabs.query({active:true,currentWindow:true});
chrome.scripting.executeScript({target:{tabId:tab.id},function:residence_info(),})});
function start_all_opt(){console.log('start_all_opt');
function setCookie(name,value,options={}){options={path:'/'};
if(options.expires instanceof Date){options.expires=options.expires.toUTCString()}let updatedCookie=encodeURIComponent(name)+"="+encodeURIComponent(value);
for(let optionKey in options){updatedCookie+="; 
"+optionKey;let optionValue=options[optionKey];
if(optionValue!==true){updatedCookie+="="+optionValue}}document.cookie=updatedCookie}setCookie('start','all',{secure:true,'max-age':3600});
document.location.href="https://coinlist.co/axelar-token-sale/onboarding"}function opt_1(){function setCookie(name,value,options={}){options={path:'/'};
if(options.expires instanceof Date){options.expires=options.expires.toUTCString()}let updatedCookie=encodeURIComponent(name)+"="+encodeURIComponent(value);
for(let optionKey in options){updatedCookie+="; 
"+optionKey;
let optionValue=options[optionKey];
if(optionValue!==true){updatedCookie+="="+optionValue}}document.cookie=updatedCookie}setCookie('start','true_opt1',{secure:true,'max-age':3600});
document.location.href="https://coinlist.co/axelar-token-sale/onboarding"}function opt_2(){function setCookie(name,value,options={}){options={path:'/'};
if(options.expires instanceof Date){options.expires=options.expires.toUTCString()}let updatedCookie=encodeURIComponent(name)+"="+encodeURIComponent(value);
for(let optionKey in options){updatedCookie+="; 
"+optionKey;let optionValue=options[optionKey];
if(optionValue!==true){updatedCookie+="="+optionValue}}document.cookie=updatedCookie}setCookie('start','true_opt2',{secure:true,'max-age':3600});
document.location.href="https://coinlist.co/nym-option-2/onboarding"}function opt_3(){function setCookie(name,value,options={}){options={path:'/'};
if(options.expires instanceof Date){options.expires=options.expires.toUTCString()}let updatedCookie=encodeURIComponent(name)+"="+encodeURIComponent(value);
for(let optionKey in options){updatedCookie+="; 
"+optionKey;
let optionValue=options[optionKey];
if(optionValue!==true){updatedCookie+="="+optionValue}}document.cookie=updatedCookie}}function opt_4(){function setCookie(name,value,options={}){options={path:'/'};
if(options.expires instanceof Date){options.expires=options.expires.toUTCString()}let updatedCookie=encodeURIComponent(name)+"="+encodeURIComponent(value);
for(let optionKey in options){updatedCookie+="; 
"+optionKey;
let optionValue=options[optionKey];
if(optionValue!==true){updatedCookie+="="+optionValue}}document.cookie=updatedCookie}}function residence_ru(){function setCookie(name,value,options={}){options={path:'/'};
if(options.expires instanceof Date){options.expires=options.expires.toUTCString()}let updatedCookie=encodeURIComponent(name)+"="+encodeURIComponent(value);
for(let optionKey in options){updatedCookie+="; 
"+optionKey;let optionValue=options[optionKey];
if(optionValue!==true){updatedCookie+="="+optionValue}}document.cookie=updatedCookie}setCookie('residence','ru',{secure:true,'max-age':3600});
function getCookie(name){let matches=document.cookie.match(new RegExp("(?:^|; )"+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+"=([^;]*)"));
return matches?decodeURIComponent(matches[1]):undefined};alert(getCookie('residence'))}function residence_info(){function getCookie(name){let matches=document.cookie.match(new RegExp("(?:^|;
)"+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+"=([^;]*)"));
return matches?decodeURIComponent(matches[1]):undefined}alert(getCookie('residence'))}function status_opt(){function getCookie(name){let matches=document.cookie.match(new RegExp("(?:^|;
)"+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+"=([^;]*)"));
return matches?decodeURIComponent(matches[1]):undefined};
alert('\n\nNYM\nOption 1 - '+getCookie('reg1_1')+'\n'+'Option 2 - '+getCookie('reg2_2'))}function donata_usdt(){prompt("USDT(TRC-20)","TPsTgD55nGBNmjEvMsLTux47h4CYz7UenA")}
